
let dc_str = "http://purl.org/dc/terms/";;
let dc = Iri.of_string dc_str ;;
let dc_ s = Iri.of_string (dc_str ^ s);;

let abstract = dc_ "abstract" ;;
let accessRights = dc_ "accessRights" ;;
let accrualMethod = dc_ "accrualMethod" ;;
let accrualPeriodicity = dc_ "accrualPeriodicity" ;;
let accrualPolicy = dc_ "accrualPolicy" ;;
let c_Agent = dc_ "Agent" ;;
let c_AgentClass = dc_ "AgentClass" ;;
let alternative = dc_ "alternative" ;;
let audience = dc_ "audience" ;;
let available = dc_ "available" ;;
let bibliographicCitation = dc_ "bibliographicCitation" ;;
let c_BibliographicResource = dc_ "BibliographicResource" ;;
let dt_Box = dc_ "Box" ;;
let conformsTo = dc_ "conformsTo" ;;
let contributor = dc_ "contributor" ;;
let coverage = dc_ "coverage" ;;
let created = dc_ "created" ;;
let creator = dc_ "creator" ;;
let date = dc_ "date" ;;
let dateAccepted = dc_ "dateAccepted" ;;
let dateCopyrighted = dc_ "dateCopyrighted" ;;
let dateSubmitted = dc_ "dateSubmitted" ;;
let description = dc_ "description" ;;
let educationLevel = dc_ "educationLevel" ;;
let extent = dc_ "extent" ;;
let c_FileFormat = dc_ "FileFormat" ;;
let format = dc_ "format" ;;
let c_Frequency = dc_ "Frequency" ;;
let hasFormat = dc_ "hasFormat" ;;
let hasPart = dc_ "hasPart" ;;
let hasVersion = dc_ "hasVersion" ;;
let identifier = dc_ "identifier" ;;
let instructionalMethod = dc_ "instructionalMethod" ;;
let isFormatOf = dc_ "isFormatOf" ;;
let dt_ISO3166 = dc_ "ISO3166" ;;
let dt_ISO639_2 = dc_ "ISO639-2" ;;
let dt_ISO639_3 = dc_ "ISO639-3" ;;
let isPartOf = dc_ "isPartOf" ;;
let isReferencedBy = dc_ "isReferencedBy" ;;
let isReplacedBy = dc_ "isReplacedBy" ;;
let isRequiredBy = dc_ "isRequiredBy" ;;
let issued = dc_ "issued" ;;
let isVersionOf = dc_ "isVersionOf" ;;
let c_Jurisdiction = dc_ "Jurisdiction" ;;
let language = dc_ "language" ;;
let license = dc_ "license" ;;
let c_LicenseDocument = dc_ "LicenseDocument" ;;
let c_LinguisticSystem = dc_ "LinguisticSystem" ;;
let c_Location = dc_ "Location" ;;
let c_LocationPeriodOrJurisdiction = dc_ "LocationPeriodOrJurisdiction" ;;
let mediator = dc_ "mediator" ;;
let c_MediaType = dc_ "MediaType" ;;
let c_MediaTypeOrExtent = dc_ "MediaTypeOrExtent" ;;
let medium = dc_ "medium" ;;
let c_MethodOfAccrual = dc_ "MethodOfAccrual" ;;
let c_MethodOfInstruction = dc_ "MethodOfInstruction" ;;
let modified = dc_ "modified" ;;
let dt_Period = dc_ "Period" ;;
let c_PeriodOfTime = dc_ "PeriodOfTime" ;;
let c_PhysicalMedium = dc_ "PhysicalMedium" ;;
let c_PhysicalResource = dc_ "PhysicalResource" ;;
let dt_Point = dc_ "Point" ;;
let c_Policy = dc_ "Policy" ;;
let provenance = dc_ "provenance" ;;
let c_ProvenanceStatement = dc_ "ProvenanceStatement" ;;
let publisher = dc_ "publisher" ;;
let references = dc_ "references" ;;
let relation = dc_ "relation" ;;
let replaces = dc_ "replaces" ;;
let requires = dc_ "requires" ;;
let dt_RFC1766 = dc_ "RFC1766" ;;
let dt_RFC3066 = dc_ "RFC3066" ;;
let dt_RFC4646 = dc_ "RFC4646" ;;
let dt_RFC5646 = dc_ "RFC5646" ;;
let rights = dc_ "rights" ;;
let rightsHolder = dc_ "rightsHolder" ;;
let c_RightsStatement = dc_ "RightsStatement" ;;
let c_SizeOrDuration = dc_ "SizeOrDuration" ;;
let source = dc_ "source" ;;
let spatial = dc_ "spatial" ;;
let c_Standard = dc_ "Standard" ;;
let subject = dc_ "subject" ;;
let tableOfContents = dc_ "tableOfContents" ;;
let temporal = dc_ "temporal" ;;
let title = dc_ "title" ;;
let type_ = dc_ "type" ;;
let dt_URI = dc_ "URI" ;;
let valid = dc_ "valid" ;;
let dt_W3CDTF = dc_ "W3CDTF" ;;

module Open = struct
  let dc_abstract = abstract
  let dc_accessRights = accessRights
  let dc_accrualMethod = accrualMethod
  let dc_accrualPeriodicity = accrualPeriodicity
  let dc_accrualPolicy = accrualPolicy
  let dc_c_Agent = c_Agent
  let dc_c_AgentClass = c_AgentClass
  let dc_alternative = alternative
  let dc_audience = audience
  let dc_available = available
  let dc_bibliographicCitation = bibliographicCitation
  let dc_c_BibliographicResource = c_BibliographicResource
  let dc_dt_Box = dt_Box
  let dc_conformsTo = conformsTo
  let dc_contributor = contributor
  let dc_coverage = coverage
  let dc_created = created
  let dc_creator = creator
  let dc_date = date
  let dc_dateAccepted = dateAccepted
  let dc_dateCopyrighted = dateCopyrighted
  let dc_dateSubmitted = dateSubmitted
  let dc_description = description
  let dc_educationLevel = educationLevel
  let dc_extent = extent
  let dc_c_FileFormat = c_FileFormat
  let dc_format = format
  let dc_c_Frequency = c_Frequency
  let dc_hasFormat = hasFormat
  let dc_hasPart = hasPart
  let dc_hasVersion = hasVersion
  let dc_identifier = identifier
  let dc_instructionalMethod = instructionalMethod
  let dc_isFormatOf = isFormatOf
  let dc_dt_ISO3166 = dt_ISO3166
  let dc_dt_ISO639_2 = dt_ISO639_2
  let dc_dt_ISO639_3 = dt_ISO639_3
  let dc_isPartOf = isPartOf
  let dc_isReferencedBy = isReferencedBy
  let dc_isReplacedBy = isReplacedBy
  let dc_isRequiredBy = isRequiredBy
  let dc_issued = issued
  let dc_isVersionOf = isVersionOf
  let dc_c_Jurisdiction = c_Jurisdiction
  let dc_language = language
  let dc_license = license
  let dc_c_LicenseDocument = c_LicenseDocument
  let dc_c_LinguisticSystem = c_LinguisticSystem
  let dc_c_Location = c_Location
  let dc_c_LocationPeriodOrJurisdiction = c_LocationPeriodOrJurisdiction
  let dc_mediator = mediator
  let dc_c_MediaType = c_MediaType
  let dc_c_MediaTypeOrExtent = c_MediaTypeOrExtent
  let dc_medium = medium
  let dc_c_MethodOfAccrual = c_MethodOfAccrual
  let dc_c_MethodOfInstruction = c_MethodOfInstruction
  let dc_modified = modified
  let dc_dt_Period = dt_Period
  let dc_c_PeriodOfTime = c_PeriodOfTime
  let dc_c_PhysicalMedium = c_PhysicalMedium
  let dc_c_PhysicalResource = c_PhysicalResource
  let dc_dt_Point = dt_Point
  let dc_c_Policy = c_Policy
  let dc_provenance = provenance
  let dc_c_ProvenanceStatement = c_ProvenanceStatement
  let dc_publisher = publisher
  let dc_references = references
  let dc_relation = relation
  let dc_replaces = replaces
  let dc_requires = requires
  let dc_dt_RFC1766 = dt_RFC1766
  let dc_dt_RFC3066 = dt_RFC3066
  let dc_dt_RFC4646 = dt_RFC4646
  let dc_dt_RFC5646 = dt_RFC5646
  let dc_rights = rights
  let dc_rightsHolder = rightsHolder
  let dc_c_RightsStatement = c_RightsStatement
  let dc_c_SizeOrDuration = c_SizeOrDuration
  let dc_source = source
  let dc_spatial = spatial
  let dc_c_Standard = c_Standard
  let dc_subject = subject
  let dc_tableOfContents = tableOfContents
  let dc_temporal = temporal
  let dc_title = title
  let dc_type = type_
  let dc_dt_URI = dt_URI
  let dc_valid = valid
  let dc_dt_W3CDTF = dt_W3CDTF
end
