
let foaf_str = "http://xmlns.com/foaf/0.1/";;
let foaf = Iri.of_string foaf_str ;;
let foaf_ s = Iri.of_string (foaf_str ^ s);;

let c_Agent = foaf_ "Agent" ;;
let c_Document = foaf_ "Document" ;;
let c_Group = foaf_ "Group" ;;
let c_Image = foaf_ "Image" ;;
let c_LabelProperty = foaf_ "LabelProperty" ;;
let c_OnlineAccount = foaf_ "OnlineAccount" ;;
let c_OnlineChatAccount = foaf_ "OnlineChatAccount" ;;
let c_OnlineEcommerceAccount = foaf_ "OnlineEcommerceAccount" ;;
let c_OnlineGamingAccount = foaf_ "OnlineGamingAccount" ;;
let c_Organization = foaf_ "Organization" ;;
let c_Person = foaf_ "Person" ;;
let c_PersonalProfileDocument = foaf_ "PersonalProfileDocument" ;;
let c_Project = foaf_ "Project" ;;
let account = foaf_ "account" ;;
let accountName = foaf_ "accountName" ;;
let accountServiceHomepage = foaf_ "accountServiceHomepage" ;;
let age = foaf_ "age" ;;
let aimChatID = foaf_ "aimChatID" ;;
let based_near = foaf_ "based_near" ;;
let birthday = foaf_ "birthday" ;;
let currentProject = foaf_ "currentProject" ;;
let depiction = foaf_ "depiction" ;;
let depicts = foaf_ "depicts" ;;
let dnaChecksum = foaf_ "dnaChecksum" ;;
let familyName = foaf_ "familyName" ;;
let family_name = foaf_ "family_name" ;;
let firstName = foaf_ "firstName" ;;
let focus = foaf_ "focus" ;;
let fundedBy = foaf_ "fundedBy" ;;
let geekcode = foaf_ "geekcode" ;;
let gender = foaf_ "gender" ;;
let givenName = foaf_ "givenName" ;;
let givenname = foaf_ "givenname" ;;
let holdsAccount = foaf_ "holdsAccount" ;;
let homepage = foaf_ "homepage" ;;
let icqChatID = foaf_ "icqChatID" ;;
let img = foaf_ "img" ;;
let interest = foaf_ "interest" ;;
let isPrimaryTopicOf = foaf_ "isPrimaryTopicOf" ;;
let jabberID = foaf_ "jabberID" ;;
let knows = foaf_ "knows" ;;
let lastName = foaf_ "lastName" ;;
let logo = foaf_ "logo" ;;
let made = foaf_ "made" ;;
let maker = foaf_ "maker" ;;
let mbox = foaf_ "mbox" ;;
let mbox_sha1sum = foaf_ "mbox_sha1sum" ;;
let member = foaf_ "member" ;;
let membershipClass = foaf_ "membershipClass" ;;
let msnChatID = foaf_ "msnChatID" ;;
let myersBriggs = foaf_ "myersBriggs" ;;
let name = foaf_ "name" ;;
let nick = foaf_ "nick" ;;
let openid = foaf_ "openid" ;;
let page = foaf_ "page" ;;
let pastProject = foaf_ "pastProject" ;;
let phone = foaf_ "phone" ;;
let plan = foaf_ "plan" ;;
let primaryTopic = foaf_ "primaryTopic" ;;
let publications = foaf_ "publications" ;;
let schoolHomepage = foaf_ "schoolHomepage" ;;
let sha1 = foaf_ "sha1" ;;
let skypeID = foaf_ "skypeID" ;;
let status = foaf_ "status" ;;
let surname = foaf_ "surname" ;;
let theme = foaf_ "theme" ;;
let thumbnail = foaf_ "thumbnail" ;;
let tipjar = foaf_ "tipjar" ;;
let title = foaf_ "title" ;;
let topic = foaf_ "topic" ;;
let topic_interest = foaf_ "topic_interest" ;;
let weblog = foaf_ "weblog" ;;
let workInfoHomepage = foaf_ "workInfoHomepage" ;;
let workplaceHomepage = foaf_ "workplaceHomepage" ;;
let yahooChatID = foaf_ "yahooChatID" ;;

module Open = struct
  let foaf_c_Agent = c_Agent
  let foaf_c_Document = c_Document
  let foaf_c_Group = c_Group
  let foaf_c_Image = c_Image
  let foaf_c_LabelProperty = c_LabelProperty
  let foaf_c_OnlineAccount = c_OnlineAccount
  let foaf_c_OnlineChatAccount = c_OnlineChatAccount
  let foaf_c_OnlineEcommerceAccount = c_OnlineEcommerceAccount
  let foaf_c_OnlineGamingAccount = c_OnlineGamingAccount
  let foaf_c_Organization = c_Organization
  let foaf_c_Person = c_Person
  let foaf_c_PersonalProfileDocument = c_PersonalProfileDocument
  let foaf_c_Project = c_Project
  let foaf_account = account
  let foaf_accountName = accountName
  let foaf_accountServiceHomepage = accountServiceHomepage
  let foaf_age = age
  let foaf_aimChatID = aimChatID
  let foaf_based_near = based_near
  let foaf_birthday = birthday
  let foaf_currentProject = currentProject
  let foaf_depiction = depiction
  let foaf_depicts = depicts
  let foaf_dnaChecksum = dnaChecksum
  let foaf_familyName = familyName
  let foaf_family_name = family_name
  let foaf_firstName = firstName
  let foaf_focus = focus
  let foaf_fundedBy = fundedBy
  let foaf_geekcode = geekcode
  let foaf_gender = gender
  let foaf_givenName = givenName
  let foaf_givenname = givenname
  let foaf_holdsAccount = holdsAccount
  let foaf_homepage = homepage
  let foaf_icqChatID = icqChatID
  let foaf_img = img
  let foaf_interest = interest
  let foaf_isPrimaryTopicOf = isPrimaryTopicOf
  let foaf_jabberID = jabberID
  let foaf_knows = knows
  let foaf_lastName = lastName
  let foaf_logo = logo
  let foaf_made = made
  let foaf_maker = maker
  let foaf_mbox = mbox
  let foaf_mbox_sha1sum = mbox_sha1sum
  let foaf_member = member
  let foaf_membershipClass = membershipClass
  let foaf_msnChatID = msnChatID
  let foaf_myersBriggs = myersBriggs
  let foaf_name = name
  let foaf_nick = nick
  let foaf_openid = openid
  let foaf_page = page
  let foaf_pastProject = pastProject
  let foaf_phone = phone
  let foaf_plan = plan
  let foaf_primaryTopic = primaryTopic
  let foaf_publications = publications
  let foaf_schoolHomepage = schoolHomepage
  let foaf_sha1 = sha1
  let foaf_skypeID = skypeID
  let foaf_status = status
  let foaf_surname = surname
  let foaf_theme = theme
  let foaf_thumbnail = thumbnail
  let foaf_tipjar = tipjar
  let foaf_title = title
  let foaf_topic = topic
  let foaf_topic_interest = topic_interest
  let foaf_weblog = weblog
  let foaf_workInfoHomepage = workInfoHomepage
  let foaf_workplaceHomepage = workplaceHomepage
  let foaf_yahooChatID = yahooChatID
end

class from ?sub g =
  let sub = match sub with None -> g.Rdf_graph.name() | Some iri -> iri in
  let sub = Rdf_term.Iri sub in
  object
  method account = Rdf_graph.iri_objects_of g ~sub ~pred: account
  method accountName = Rdf_graph.literal_objects_of g ~sub ~pred: accountName
  method accountServiceHomepage = Rdf_graph.iri_objects_of g ~sub ~pred: accountServiceHomepage
  method age = Rdf_graph.literal_objects_of g ~sub ~pred: age
  method aimChatID = Rdf_graph.literal_objects_of g ~sub ~pred: aimChatID
  method based_near = Rdf_graph.iri_objects_of g ~sub ~pred: based_near
  method birthday = Rdf_graph.literal_objects_of g ~sub ~pred: birthday
  method currentProject = Rdf_graph.iri_objects_of g ~sub ~pred: currentProject
  method depiction = Rdf_graph.iri_objects_of g ~sub ~pred: depiction
  method depicts = Rdf_graph.iri_objects_of g ~sub ~pred: depicts
  method dnaChecksum = Rdf_graph.literal_objects_of g ~sub ~pred: dnaChecksum
  method familyName = Rdf_graph.literal_objects_of g ~sub ~pred: familyName
  method family_name = Rdf_graph.literal_objects_of g ~sub ~pred: family_name
  method firstName = Rdf_graph.literal_objects_of g ~sub ~pred: firstName
  method focus = Rdf_graph.iri_objects_of g ~sub ~pred: focus
  method fundedBy = Rdf_graph.iri_objects_of g ~sub ~pred: fundedBy
  method geekcode = Rdf_graph.literal_objects_of g ~sub ~pred: geekcode
  method gender = Rdf_graph.literal_objects_of g ~sub ~pred: gender
  method givenName = Rdf_graph.iri_objects_of g ~sub ~pred: givenName
  method givenname = Rdf_graph.iri_objects_of g ~sub ~pred: givenname
  method holdsAccount = Rdf_graph.iri_objects_of g ~sub ~pred: holdsAccount
  method homepage = Rdf_graph.iri_objects_of g ~sub ~pred: homepage
  method icqChatID = Rdf_graph.literal_objects_of g ~sub ~pred: icqChatID
  method img = Rdf_graph.iri_objects_of g ~sub ~pred: img
  method interest = Rdf_graph.iri_objects_of g ~sub ~pred: interest
  method isPrimaryTopicOf = Rdf_graph.iri_objects_of g ~sub ~pred: isPrimaryTopicOf
  method jabberID = Rdf_graph.literal_objects_of g ~sub ~pred: jabberID
  method knows = Rdf_graph.iri_objects_of g ~sub ~pred: knows
  method lastName = Rdf_graph.literal_objects_of g ~sub ~pred: lastName
  method logo = Rdf_graph.iri_objects_of g ~sub ~pred: logo
  method made = Rdf_graph.iri_objects_of g ~sub ~pred: made
  method maker = Rdf_graph.iri_objects_of g ~sub ~pred: maker
  method mbox = Rdf_graph.iri_objects_of g ~sub ~pred: mbox
  method mbox_sha1sum = Rdf_graph.literal_objects_of g ~sub ~pred: mbox_sha1sum
  method member = Rdf_graph.iri_objects_of g ~sub ~pred: member
  method membershipClass = Rdf_graph.iri_objects_of g ~sub ~pred: membershipClass
  method msnChatID = Rdf_graph.literal_objects_of g ~sub ~pred: msnChatID
  method myersBriggs = Rdf_graph.literal_objects_of g ~sub ~pred: myersBriggs
  method name = Rdf_graph.literal_objects_of g ~sub ~pred: name
  method nick = Rdf_graph.iri_objects_of g ~sub ~pred: nick
  method openid = Rdf_graph.iri_objects_of g ~sub ~pred: openid
  method page = Rdf_graph.iri_objects_of g ~sub ~pred: page
  method pastProject = Rdf_graph.iri_objects_of g ~sub ~pred: pastProject
  method phone = Rdf_graph.iri_objects_of g ~sub ~pred: phone
  method plan = Rdf_graph.literal_objects_of g ~sub ~pred: plan
  method primaryTopic = Rdf_graph.iri_objects_of g ~sub ~pred: primaryTopic
  method publications = Rdf_graph.iri_objects_of g ~sub ~pred: publications
  method schoolHomepage = Rdf_graph.iri_objects_of g ~sub ~pred: schoolHomepage
  method sha1 = Rdf_graph.iri_objects_of g ~sub ~pred: sha1
  method skypeID = Rdf_graph.literal_objects_of g ~sub ~pred: skypeID
  method status = Rdf_graph.literal_objects_of g ~sub ~pred: status
  method surname = Rdf_graph.literal_objects_of g ~sub ~pred: surname
  method theme = Rdf_graph.iri_objects_of g ~sub ~pred: theme
  method thumbnail = Rdf_graph.iri_objects_of g ~sub ~pred: thumbnail
  method tipjar = Rdf_graph.iri_objects_of g ~sub ~pred: tipjar
  method title = Rdf_graph.iri_objects_of g ~sub ~pred: title
  method topic = Rdf_graph.iri_objects_of g ~sub ~pred: topic
  method topic_interest = Rdf_graph.iri_objects_of g ~sub ~pred: topic_interest
  method weblog = Rdf_graph.iri_objects_of g ~sub ~pred: weblog
  method workInfoHomepage = Rdf_graph.iri_objects_of g ~sub ~pred: workInfoHomepage
  method workplaceHomepage = Rdf_graph.iri_objects_of g ~sub ~pred: workplaceHomepage
  method yahooChatID = Rdf_graph.literal_objects_of g ~sub ~pred: yahooChatID
  end
