
let time_str = "http://www.w3.org/2006/time#";;
let time = Iri.of_string time_str ;;
let time_ s = Iri.of_string (time_str ^ s);;

let c_DateTimeDescription = time_ "DateTimeDescription" ;;
let c_DateTimeInterval = time_ "DateTimeInterval" ;;
let c_DayOfWeek = time_ "DayOfWeek" ;;
let c_Duration = time_ "Duration" ;;
let c_DurationDescription = time_ "DurationDescription" ;;
let c_GeneralDateTimeDescription = time_ "GeneralDateTimeDescription" ;;
let c_GeneralDurationDescription = time_ "GeneralDurationDescription" ;;
let c_Instant = time_ "Instant" ;;
let c_Interval = time_ "Interval" ;;
let dt_Number = time_ "Number" ;;
let c_ProperInterval = time_ "ProperInterval" ;;
let c_TRS = time_ "TRS" ;;
let c_TemporalEntity = time_ "TemporalEntity" ;;
let c_TemporalUnit = time_ "TemporalUnit" ;;
let c_TimePosition = time_ "TimePosition" ;;
let c_Year = time_ "Year" ;;
let day = time_ "day" ;;
let dayOfYear = time_ "dayOfYear" ;;
let days = time_ "days" ;;
let dt_generalDay = time_ "generalDay" ;;
let dt_generalMonth = time_ "generalMonth" ;;
let dt_generalYear = time_ "generalYear" ;;
let hour = time_ "hour" ;;
let hours = time_ "hours" ;;
let inXSDDateTime = time_ "inXSDDateTime" ;;
let minute = time_ "minute" ;;
let minutes = time_ "minutes" ;;
let month = time_ "month" ;;
let months = time_ "months" ;;
let nominalPosition = time_ "nominalPosition" ;;
let numericDuration = time_ "numericDuration" ;;
let numericPosition = time_ "numericPosition" ;;
let second = time_ "second" ;;
let seconds = time_ "seconds" ;;
let week = time_ "week" ;;
let weeks = time_ "weeks" ;;
let xsdDateTime = time_ "xsdDateTime" ;;
let year = time_ "year" ;;
let years = time_ "years" ;;

module Open = struct
  let time_c_DateTimeDescription = c_DateTimeDescription
  let time_c_DateTimeInterval = c_DateTimeInterval
  let time_c_DayOfWeek = c_DayOfWeek
  let time_c_Duration = c_Duration
  let time_c_DurationDescription = c_DurationDescription
  let time_c_GeneralDateTimeDescription = c_GeneralDateTimeDescription
  let time_c_GeneralDurationDescription = c_GeneralDurationDescription
  let time_c_Instant = c_Instant
  let time_c_Interval = c_Interval
  let time_dt_Number = dt_Number
  let time_c_ProperInterval = c_ProperInterval
  let time_c_TRS = c_TRS
  let time_c_TemporalEntity = c_TemporalEntity
  let time_c_TemporalUnit = c_TemporalUnit
  let time_c_TimePosition = c_TimePosition
  let time_c_Year = c_Year
  let time_day = day
  let time_dayOfYear = dayOfYear
  let time_days = days
  let time_dt_generalDay = dt_generalDay
  let time_dt_generalMonth = dt_generalMonth
  let time_dt_generalYear = dt_generalYear
  let time_hour = hour
  let time_hours = hours
  let time_inXSDDateTime = inXSDDateTime
  let time_minute = minute
  let time_minutes = minutes
  let time_month = month
  let time_months = months
  let time_nominalPosition = nominalPosition
  let time_numericDuration = numericDuration
  let time_numericPosition = numericPosition
  let time_second = second
  let time_seconds = seconds
  let time_week = week
  let time_weeks = weeks
  let time_xsdDateTime = xsdDateTime
  let time_year = year
  let time_years = years
end

class from ?sub g =
  let sub = match sub with None -> g.Rdf_graph.name() | Some iri -> iri in
  let sub = Rdf_term.Iri sub in
  object
  method day = Rdf_graph.iri_objects_of g ~sub ~pred: day
  method dayOfYear = Rdf_graph.iri_objects_of g ~sub ~pred: dayOfYear
  method days = Rdf_graph.iri_objects_of g ~sub ~pred: days
  method hour = Rdf_graph.iri_objects_of g ~sub ~pred: hour
  method hours = Rdf_graph.iri_objects_of g ~sub ~pred: hours
  method inXSDDateTime = Rdf_graph.iri_objects_of g ~sub ~pred: inXSDDateTime
  method minute = Rdf_graph.iri_objects_of g ~sub ~pred: minute
  method minutes = Rdf_graph.iri_objects_of g ~sub ~pred: minutes
  method month = Rdf_graph.iri_objects_of g ~sub ~pred: month
  method months = Rdf_graph.iri_objects_of g ~sub ~pred: months
  method nominalPosition = Rdf_graph.iri_objects_of g ~sub ~pred: nominalPosition
  method numericDuration = Rdf_graph.iri_objects_of g ~sub ~pred: numericDuration
  method numericPosition = Rdf_graph.iri_objects_of g ~sub ~pred: numericPosition
  method second = Rdf_graph.iri_objects_of g ~sub ~pred: second
  method seconds = Rdf_graph.iri_objects_of g ~sub ~pred: seconds
  method week = Rdf_graph.iri_objects_of g ~sub ~pred: week
  method weeks = Rdf_graph.iri_objects_of g ~sub ~pred: weeks
  method xsdDateTime = Rdf_graph.iri_objects_of g ~sub ~pred: xsdDateTime
  method year = Rdf_graph.iri_objects_of g ~sub ~pred: year
  method years = Rdf_graph.iri_objects_of g ~sub ~pred: years
  end
