
let dc_str = "http://purl.org/dc/terms/";;
let dc = Iri.of_string dc_str ;;
let dc_ s = Iri.of_string (dc_str ^ s);;

let abstract = dc_ "abstract" ;;
let accessRights = dc_ "accessRights" ;;
let accrualMethod = dc_ "accrualMethod" ;;
let accrualPeriodicity = dc_ "accrualPeriodicity" ;;
let accrualPolicy = dc_ "accrualPolicy" ;;
let agent = dc_ "Agent" ;;
let agentClass = dc_ "AgentClass" ;;
let alternative = dc_ "alternative" ;;
let audience = dc_ "audience" ;;
let available = dc_ "available" ;;
let bibliographicCitation = dc_ "bibliographicCitation" ;;
let bibliographicResource = dc_ "BibliographicResource" ;;
let box = dc_ "Box" ;;
let conformsTo = dc_ "conformsTo" ;;
let contributor = dc_ "contributor" ;;
let coverage = dc_ "coverage" ;;
let created = dc_ "created" ;;
let creator = dc_ "creator" ;;
let date = dc_ "date" ;;
let dateAccepted = dc_ "dateAccepted" ;;
let dateCopyrighted = dc_ "dateCopyrighted" ;;
let dateSubmitted = dc_ "dateSubmitted" ;;
let description = dc_ "description" ;;
let educationLevel = dc_ "educationLevel" ;;
let extent = dc_ "extent" ;;
let fileFormat = dc_ "FileFormat" ;;
let format = dc_ "format" ;;
let frequency = dc_ "Frequency" ;;
let hasFormat = dc_ "hasFormat" ;;
let hasPart = dc_ "hasPart" ;;
let hasVersion = dc_ "hasVersion" ;;
let identifier = dc_ "identifier" ;;
let instructionalMethod = dc_ "instructionalMethod" ;;
let isFormatOf = dc_ "isFormatOf" ;;
let iSO3166 = dc_ "ISO3166" ;;
let iSO639_2 = dc_ "ISO639-2" ;;
let iSO639_3 = dc_ "ISO639-3" ;;
let isPartOf = dc_ "isPartOf" ;;
let isReferencedBy = dc_ "isReferencedBy" ;;
let isReplacedBy = dc_ "isReplacedBy" ;;
let isRequiredBy = dc_ "isRequiredBy" ;;
let issued = dc_ "issued" ;;
let isVersionOf = dc_ "isVersionOf" ;;
let jurisdiction = dc_ "Jurisdiction" ;;
let language = dc_ "language" ;;
let license = dc_ "license" ;;
let licenseDocument = dc_ "LicenseDocument" ;;
let linguisticSystem = dc_ "LinguisticSystem" ;;
let location = dc_ "Location" ;;
let locationPeriodOrJurisdiction = dc_ "LocationPeriodOrJurisdiction" ;;
let mediator = dc_ "mediator" ;;
let mediaType = dc_ "MediaType" ;;
let mediaTypeOrExtent = dc_ "MediaTypeOrExtent" ;;
let medium = dc_ "medium" ;;
let methodOfAccrual = dc_ "MethodOfAccrual" ;;
let methodOfInstruction = dc_ "MethodOfInstruction" ;;
let modified = dc_ "modified" ;;
let period = dc_ "Period" ;;
let periodOfTime = dc_ "PeriodOfTime" ;;
let physicalMedium = dc_ "PhysicalMedium" ;;
let physicalResource = dc_ "PhysicalResource" ;;
let point = dc_ "Point" ;;
let policy = dc_ "Policy" ;;
let provenance = dc_ "provenance" ;;
let provenanceStatement = dc_ "ProvenanceStatement" ;;
let publisher = dc_ "publisher" ;;
let references = dc_ "references" ;;
let relation = dc_ "relation" ;;
let replaces = dc_ "replaces" ;;
let requires = dc_ "requires" ;;
let rFC1766 = dc_ "RFC1766" ;;
let rFC3066 = dc_ "RFC3066" ;;
let rFC4646 = dc_ "RFC4646" ;;
let rFC5646 = dc_ "RFC5646" ;;
let rights = dc_ "rights" ;;
let rightsHolder = dc_ "rightsHolder" ;;
let rightsStatement = dc_ "RightsStatement" ;;
let sizeOrDuration = dc_ "SizeOrDuration" ;;
let source = dc_ "source" ;;
let spatial = dc_ "spatial" ;;
let standard = dc_ "Standard" ;;
let subject = dc_ "subject" ;;
let tableOfContents = dc_ "tableOfContents" ;;
let temporal = dc_ "temporal" ;;
let title = dc_ "title" ;;
let type_ = dc_ "type" ;;
let uRI = dc_ "URI" ;;
let valid = dc_ "valid" ;;
let w3CDTF = dc_ "W3CDTF" ;;

module Open = struct
  let dc_abstract = abstract
  let dc_accessRights = accessRights
  let dc_accrualMethod = accrualMethod
  let dc_accrualPeriodicity = accrualPeriodicity
  let dc_accrualPolicy = accrualPolicy
  let dc_agent = agent
  let dc_agentClass = agentClass
  let dc_alternative = alternative
  let dc_audience = audience
  let dc_available = available
  let dc_bibliographicCitation = bibliographicCitation
  let dc_bibliographicResource = bibliographicResource
  let dc_box = box
  let dc_conformsTo = conformsTo
  let dc_contributor = contributor
  let dc_coverage = coverage
  let dc_created = created
  let dc_creator = creator
  let dc_date = date
  let dc_dateAccepted = dateAccepted
  let dc_dateCopyrighted = dateCopyrighted
  let dc_dateSubmitted = dateSubmitted
  let dc_description = description
  let dc_educationLevel = educationLevel
  let dc_extent = extent
  let dc_fileFormat = fileFormat
  let dc_format = format
  let dc_frequency = frequency
  let dc_hasFormat = hasFormat
  let dc_hasPart = hasPart
  let dc_hasVersion = hasVersion
  let dc_identifier = identifier
  let dc_instructionalMethod = instructionalMethod
  let dc_isFormatOf = isFormatOf
  let dc_iSO3166 = iSO3166
  let dc_iSO639_2 = iSO639_2
  let dc_iSO639_3 = iSO639_3
  let dc_isPartOf = isPartOf
  let dc_isReferencedBy = isReferencedBy
  let dc_isReplacedBy = isReplacedBy
  let dc_isRequiredBy = isRequiredBy
  let dc_issued = issued
  let dc_isVersionOf = isVersionOf
  let dc_jurisdiction = jurisdiction
  let dc_language = language
  let dc_license = license
  let dc_licenseDocument = licenseDocument
  let dc_linguisticSystem = linguisticSystem
  let dc_location = location
  let dc_locationPeriodOrJurisdiction = locationPeriodOrJurisdiction
  let dc_mediator = mediator
  let dc_mediaType = mediaType
  let dc_mediaTypeOrExtent = mediaTypeOrExtent
  let dc_medium = medium
  let dc_methodOfAccrual = methodOfAccrual
  let dc_methodOfInstruction = methodOfInstruction
  let dc_modified = modified
  let dc_period = period
  let dc_periodOfTime = periodOfTime
  let dc_physicalMedium = physicalMedium
  let dc_physicalResource = physicalResource
  let dc_point = point
  let dc_policy = policy
  let dc_provenance = provenance
  let dc_provenanceStatement = provenanceStatement
  let dc_publisher = publisher
  let dc_references = references
  let dc_relation = relation
  let dc_replaces = replaces
  let dc_requires = requires
  let dc_rFC1766 = rFC1766
  let dc_rFC3066 = rFC3066
  let dc_rFC4646 = rFC4646
  let dc_rFC5646 = rFC5646
  let dc_rights = rights
  let dc_rightsHolder = rightsHolder
  let dc_rightsStatement = rightsStatement
  let dc_sizeOrDuration = sizeOrDuration
  let dc_source = source
  let dc_spatial = spatial
  let dc_standard = standard
  let dc_subject = subject
  let dc_tableOfContents = tableOfContents
  let dc_temporal = temporal
  let dc_title = title
  let dc_type = type_
  let dc_uRI = uRI
  let dc_valid = valid
  let dc_w3CDTF = w3CDTF
end
