
let sioc_str = "http://rdfs.org/sioc/ns#";;
let sioc = Iri.of_string sioc_str ;;
let sioc_ s = Iri.of_string (sioc_str ^ s);;

let c_Community = sioc_ "Community" ;;
let c_Container = sioc_ "Container" ;;
let c_Forum = sioc_ "Forum" ;;
let c_Item = sioc_ "Item" ;;
let c_Post = sioc_ "Post" ;;
let c_Role = sioc_ "Role" ;;
let c_Site = sioc_ "Site" ;;
let c_Space = sioc_ "Space" ;;
let c_Thread = sioc_ "Thread" ;;
let c_User = sioc_ "User" ;;
let c_UserAccount = sioc_ "UserAccount" ;;
let c_Usergroup = sioc_ "Usergroup" ;;
let content = sioc_ "content" ;;
let content_encoded = sioc_ "content_encoded" ;;
let created_at = sioc_ "created_at" ;;
let description = sioc_ "description" ;;
let email_sha1 = sioc_ "email_sha1" ;;
let first_name = sioc_ "first_name" ;;
let id = sioc_ "id" ;;
let ip_address = sioc_ "ip_address" ;;
let last_activity_date = sioc_ "last_activity_date" ;;
let last_item_date = sioc_ "last_item_date" ;;
let last_name = sioc_ "last_name" ;;
let last_reply_date = sioc_ "last_reply_date" ;;
let modified_at = sioc_ "modified_at" ;;
let name = sioc_ "name" ;;
let note = sioc_ "note" ;;
let num_authors = sioc_ "num_authors" ;;
let num_items = sioc_ "num_items" ;;
let num_replies = sioc_ "num_replies" ;;
let num_threads = sioc_ "num_threads" ;;
let num_views = sioc_ "num_views" ;;
let subject = sioc_ "subject" ;;
let title = sioc_ "title" ;;

module Open = struct
  let sioc_c_Community = c_Community
  let sioc_c_Container = c_Container
  let sioc_c_Forum = c_Forum
  let sioc_c_Item = c_Item
  let sioc_c_Post = c_Post
  let sioc_c_Role = c_Role
  let sioc_c_Site = c_Site
  let sioc_c_Space = c_Space
  let sioc_c_Thread = c_Thread
  let sioc_c_User = c_User
  let sioc_c_UserAccount = c_UserAccount
  let sioc_c_Usergroup = c_Usergroup
  let sioc_content = content
  let sioc_content_encoded = content_encoded
  let sioc_created_at = created_at
  let sioc_description = description
  let sioc_email_sha1 = email_sha1
  let sioc_first_name = first_name
  let sioc_id = id
  let sioc_ip_address = ip_address
  let sioc_last_activity_date = last_activity_date
  let sioc_last_item_date = last_item_date
  let sioc_last_name = last_name
  let sioc_last_reply_date = last_reply_date
  let sioc_modified_at = modified_at
  let sioc_name = name
  let sioc_note = note
  let sioc_num_authors = num_authors
  let sioc_num_items = num_items
  let sioc_num_replies = num_replies
  let sioc_num_threads = num_threads
  let sioc_num_views = num_views
  let sioc_subject = subject
  let sioc_title = title
end

class from ?sub g =
  let sub = match sub with None -> g.Rdf_graph.name() | Some iri -> iri in
  let sub = Rdf_term.Iri sub in
  object
  method content = Rdf_graph.literal_objects_of g ~sub ~pred: content
  method content_encoded = Rdf_graph.literal_objects_of g ~sub ~pred: content_encoded
  method created_at = Rdf_graph.literal_objects_of g ~sub ~pred: created_at
  method description = Rdf_graph.literal_objects_of g ~sub ~pred: description
  method email_sha1 = Rdf_graph.literal_objects_of g ~sub ~pred: email_sha1
  method first_name = Rdf_graph.literal_objects_of g ~sub ~pred: first_name
  method id = Rdf_graph.literal_objects_of g ~sub ~pred: id
  method ip_address = Rdf_graph.literal_objects_of g ~sub ~pred: ip_address
  method last_activity_date = Rdf_graph.literal_objects_of g ~sub ~pred: last_activity_date
  method last_item_date = Rdf_graph.literal_objects_of g ~sub ~pred: last_item_date
  method last_name = Rdf_graph.literal_objects_of g ~sub ~pred: last_name
  method last_reply_date = Rdf_graph.literal_objects_of g ~sub ~pred: last_reply_date
  method modified_at = Rdf_graph.literal_objects_of g ~sub ~pred: modified_at
  method name = Rdf_graph.literal_objects_of g ~sub ~pred: name
  method note = Rdf_graph.literal_objects_of g ~sub ~pred: note
  method num_authors = Rdf_graph.iri_objects_of g ~sub ~pred: num_authors
  method num_items = Rdf_graph.iri_objects_of g ~sub ~pred: num_items
  method num_replies = Rdf_graph.iri_objects_of g ~sub ~pred: num_replies
  method num_threads = Rdf_graph.iri_objects_of g ~sub ~pred: num_threads
  method num_views = Rdf_graph.iri_objects_of g ~sub ~pred: num_views
  method subject = Rdf_graph.literal_objects_of g ~sub ~pred: subject
  method title = Rdf_graph.literal_objects_of g ~sub ~pred: title
  end
