
let earl_str = "http://www.w3.org/ns/earl#";;
let earl = Iri.of_string earl_str ;;
let earl_ s = Iri.of_string (earl_str ^ s);;

let assertedBy = earl_ "assertedBy" ;;
let assertion = earl_ "Assertion" ;;
let assertor = earl_ "Assertor" ;;
let cannotTell = earl_ "CannotTell" ;;
let fail = earl_ "Fail" ;;
let info = earl_ "info" ;;
let mainAssertor = earl_ "mainAssertor" ;;
let mode = earl_ "mode" ;;
let notApplicable = earl_ "NotApplicable" ;;
let notTested = earl_ "NotTested" ;;
let outcome = earl_ "outcome" ;;
let outcomeValue = earl_ "OutcomeValue" ;;
let pass = earl_ "Pass" ;;
let pointer = earl_ "pointer" ;;
let result = earl_ "result" ;;
let software = earl_ "Software" ;;
let subject = earl_ "subject" ;;
let test = earl_ "test" ;;
let testCase = earl_ "TestCase" ;;
let testCriterion = earl_ "TestCriterion" ;;
let testMode = earl_ "TestMode" ;;
let testRequirement = earl_ "TestRequirement" ;;
let testResult = earl_ "TestResult" ;;
let testSubject = earl_ "TestSubject" ;;

module Open = struct
  let earl_assertedBy = assertedBy
  let earl_assertion = assertion
  let earl_assertor = assertor
  let earl_cannotTell = cannotTell
  let earl_fail = fail
  let earl_info = info
  let earl_mainAssertor = mainAssertor
  let earl_mode = mode
  let earl_notApplicable = notApplicable
  let earl_notTested = notTested
  let earl_outcome = outcome
  let earl_outcomeValue = outcomeValue
  let earl_pass = pass
  let earl_pointer = pointer
  let earl_result = result
  let earl_software = software
  let earl_subject = subject
  let earl_test = test
  let earl_testCase = testCase
  let earl_testCriterion = testCriterion
  let earl_testMode = testMode
  let earl_testRequirement = testRequirement
  let earl_testResult = testResult
  let earl_testSubject = testSubject
end
