
let foaf_str = "http://xmlns.com/foaf/0.1/";;
let foaf = Iri.of_string foaf_str ;;
let foaf_ s = Iri.of_string (foaf_str ^ s);;

let c_Agent = foaf_ "Agent" ;;
let c_Document = foaf_ "Document" ;;
let c_Group = foaf_ "Group" ;;
let c_Image = foaf_ "Image" ;;
let c_LabelProperty = foaf_ "LabelProperty" ;;
let c_OnlineAccount = foaf_ "OnlineAccount" ;;
let c_OnlineChatAccount = foaf_ "OnlineChatAccount" ;;
let c_OnlineEcommerceAccount = foaf_ "OnlineEcommerceAccount" ;;
let c_OnlineGamingAccount = foaf_ "OnlineGamingAccount" ;;
let c_Organization = foaf_ "Organization" ;;
let c_Person = foaf_ "Person" ;;
let c_PersonalProfileDocument = foaf_ "PersonalProfileDocument" ;;
let c_Project = foaf_ "Project" ;;
let account = foaf_ "account" ;;
let accountName = foaf_ "accountName" ;;
let accountServiceHomepage = foaf_ "accountServiceHomepage" ;;
let age = foaf_ "age" ;;
let aimChatID = foaf_ "aimChatID" ;;
let based_near = foaf_ "based_near" ;;
let birthday = foaf_ "birthday" ;;
let currentProject = foaf_ "currentProject" ;;
let depiction = foaf_ "depiction" ;;
let depicts = foaf_ "depicts" ;;
let dnaChecksum = foaf_ "dnaChecksum" ;;
let familyName = foaf_ "familyName" ;;
let family_name = foaf_ "family_name" ;;
let firstName = foaf_ "firstName" ;;
let focus = foaf_ "focus" ;;
let fundedBy = foaf_ "fundedBy" ;;
let geekcode = foaf_ "geekcode" ;;
let gender = foaf_ "gender" ;;
let givenName = foaf_ "givenName" ;;
let givenname = foaf_ "givenname" ;;
let holdsAccount = foaf_ "holdsAccount" ;;
let homepage = foaf_ "homepage" ;;
let icqChatID = foaf_ "icqChatID" ;;
let img = foaf_ "img" ;;
let interest = foaf_ "interest" ;;
let isPrimaryTopicOf = foaf_ "isPrimaryTopicOf" ;;
let jabberID = foaf_ "jabberID" ;;
let knows = foaf_ "knows" ;;
let lastName = foaf_ "lastName" ;;
let logo = foaf_ "logo" ;;
let made = foaf_ "made" ;;
let maker = foaf_ "maker" ;;
let mbox = foaf_ "mbox" ;;
let mbox_sha1sum = foaf_ "mbox_sha1sum" ;;
let member = foaf_ "member" ;;
let membershipClass = foaf_ "membershipClass" ;;
let msnChatID = foaf_ "msnChatID" ;;
let myersBriggs = foaf_ "myersBriggs" ;;
let name = foaf_ "name" ;;
let nick = foaf_ "nick" ;;
let openid = foaf_ "openid" ;;
let page = foaf_ "page" ;;
let pastProject = foaf_ "pastProject" ;;
let phone = foaf_ "phone" ;;
let plan = foaf_ "plan" ;;
let primaryTopic = foaf_ "primaryTopic" ;;
let publications = foaf_ "publications" ;;
let schoolHomepage = foaf_ "schoolHomepage" ;;
let sha1 = foaf_ "sha1" ;;
let skypeID = foaf_ "skypeID" ;;
let status = foaf_ "status" ;;
let surname = foaf_ "surname" ;;
let theme = foaf_ "theme" ;;
let thumbnail = foaf_ "thumbnail" ;;
let tipjar = foaf_ "tipjar" ;;
let title = foaf_ "title" ;;
let topic = foaf_ "topic" ;;
let topic_interest = foaf_ "topic_interest" ;;
let weblog = foaf_ "weblog" ;;
let workInfoHomepage = foaf_ "workInfoHomepage" ;;
let workplaceHomepage = foaf_ "workplaceHomepage" ;;
let yahooChatID = foaf_ "yahooChatID" ;;

module Open = struct
  let foaf_c_Agent = c_Agent
  let foaf_c_Document = c_Document
  let foaf_c_Group = c_Group
  let foaf_c_Image = c_Image
  let foaf_c_LabelProperty = c_LabelProperty
  let foaf_c_OnlineAccount = c_OnlineAccount
  let foaf_c_OnlineChatAccount = c_OnlineChatAccount
  let foaf_c_OnlineEcommerceAccount = c_OnlineEcommerceAccount
  let foaf_c_OnlineGamingAccount = c_OnlineGamingAccount
  let foaf_c_Organization = c_Organization
  let foaf_c_Person = c_Person
  let foaf_c_PersonalProfileDocument = c_PersonalProfileDocument
  let foaf_c_Project = c_Project
  let foaf_account = account
  let foaf_accountName = accountName
  let foaf_accountServiceHomepage = accountServiceHomepage
  let foaf_age = age
  let foaf_aimChatID = aimChatID
  let foaf_based_near = based_near
  let foaf_birthday = birthday
  let foaf_currentProject = currentProject
  let foaf_depiction = depiction
  let foaf_depicts = depicts
  let foaf_dnaChecksum = dnaChecksum
  let foaf_familyName = familyName
  let foaf_family_name = family_name
  let foaf_firstName = firstName
  let foaf_focus = focus
  let foaf_fundedBy = fundedBy
  let foaf_geekcode = geekcode
  let foaf_gender = gender
  let foaf_givenName = givenName
  let foaf_givenname = givenname
  let foaf_holdsAccount = holdsAccount
  let foaf_homepage = homepage
  let foaf_icqChatID = icqChatID
  let foaf_img = img
  let foaf_interest = interest
  let foaf_isPrimaryTopicOf = isPrimaryTopicOf
  let foaf_jabberID = jabberID
  let foaf_knows = knows
  let foaf_lastName = lastName
  let foaf_logo = logo
  let foaf_made = made
  let foaf_maker = maker
  let foaf_mbox = mbox
  let foaf_mbox_sha1sum = mbox_sha1sum
  let foaf_member = member
  let foaf_membershipClass = membershipClass
  let foaf_msnChatID = msnChatID
  let foaf_myersBriggs = myersBriggs
  let foaf_name = name
  let foaf_nick = nick
  let foaf_openid = openid
  let foaf_page = page
  let foaf_pastProject = pastProject
  let foaf_phone = phone
  let foaf_plan = plan
  let foaf_primaryTopic = primaryTopic
  let foaf_publications = publications
  let foaf_schoolHomepage = schoolHomepage
  let foaf_sha1 = sha1
  let foaf_skypeID = skypeID
  let foaf_status = status
  let foaf_surname = surname
  let foaf_theme = theme
  let foaf_thumbnail = thumbnail
  let foaf_tipjar = tipjar
  let foaf_title = title
  let foaf_topic = topic
  let foaf_topic_interest = topic_interest
  let foaf_weblog = weblog
  let foaf_workInfoHomepage = workInfoHomepage
  let foaf_workplaceHomepage = workplaceHomepage
  let foaf_yahooChatID = yahooChatID
end

class from ?sub g =
  let sub = match sub with None -> g.Rdf_graph.name() | Some iri -> iri in
  let sub = Rdf_term.Iri sub in
  let get_prop_list pred =
    Rdf_graph.iri_objects_of g ~sub ~pred
  in
  object
  method account = get_prop_list account
  method accountName = get_prop_list accountName
  method accountServiceHomepage = get_prop_list accountServiceHomepage
  method age = get_prop_list age
  method aimChatID = get_prop_list aimChatID
  method based_near = get_prop_list based_near
  method birthday = get_prop_list birthday
  method currentProject = get_prop_list currentProject
  method depiction = get_prop_list depiction
  method depicts = get_prop_list depicts
  method dnaChecksum = get_prop_list dnaChecksum
  method familyName = get_prop_list familyName
  method family_name = get_prop_list family_name
  method firstName = get_prop_list firstName
  method focus = get_prop_list focus
  method fundedBy = get_prop_list fundedBy
  method geekcode = get_prop_list geekcode
  method gender = get_prop_list gender
  method givenName = get_prop_list givenName
  method givenname = get_prop_list givenname
  method holdsAccount = get_prop_list holdsAccount
  method homepage = get_prop_list homepage
  method icqChatID = get_prop_list icqChatID
  method img = get_prop_list img
  method interest = get_prop_list interest
  method isPrimaryTopicOf = get_prop_list isPrimaryTopicOf
  method jabberID = get_prop_list jabberID
  method knows = get_prop_list knows
  method lastName = get_prop_list lastName
  method logo = get_prop_list logo
  method made = get_prop_list made
  method maker = get_prop_list maker
  method mbox = get_prop_list mbox
  method mbox_sha1sum = get_prop_list mbox_sha1sum
  method member = get_prop_list member
  method membershipClass = get_prop_list membershipClass
  method msnChatID = get_prop_list msnChatID
  method myersBriggs = get_prop_list myersBriggs
  method name = get_prop_list name
  method nick = get_prop_list nick
  method openid = get_prop_list openid
  method page = get_prop_list page
  method pastProject = get_prop_list pastProject
  method phone = get_prop_list phone
  method plan = get_prop_list plan
  method primaryTopic = get_prop_list primaryTopic
  method publications = get_prop_list publications
  method schoolHomepage = get_prop_list schoolHomepage
  method sha1 = get_prop_list sha1
  method skypeID = get_prop_list skypeID
  method status = get_prop_list status
  method surname = get_prop_list surname
  method theme = get_prop_list theme
  method thumbnail = get_prop_list thumbnail
  method tipjar = get_prop_list tipjar
  method title = get_prop_list title
  method topic = get_prop_list topic
  method topic_interest = get_prop_list topic_interest
  method weblog = get_prop_list weblog
  method workInfoHomepage = get_prop_list workInfoHomepage
  method workplaceHomepage = get_prop_list workplaceHomepage
  method yahooChatID = get_prop_list yahooChatID
  end
